-- This is an empty migration.
INSERT INTO public."Auth" (auth_request,auth_request_headers,proxy_headers,"name") VALUES
	 ('/outpost.goauthentik.io/auth/nginx','{"$auth_cookie $upstream_http_set_cookie","$authentik_username $upstream_http_x_authentik_username","$authentik_groups $upstream_http_x_authentik_groups","$authentik_email $upstream_http_x_authentik_email","$authentik_name $upstream_http_x_authentik_name","$authentik_uid $upstream_http_x_authentik_uid"}','{"X-authentik-username $authentik_username","X-authentik-groups $authentik_groups","X-authentik-email $authentik_email","X-authentik-name $authentik_name","X-authentik-uid $authentik_uid"}','Authentik');

INSERT INTO public."Location" (prefix,"location",directives) VALUES
	 ('/','outpost.goauthentik.io','{"proxy_pass https://authentik:9443/outpost.goauthentik.io","proxy_set_header X-Original-URL $scheme://$http_host$request_uri","add_header Set-Cookie $auth_cookie","auth_request_set $auth_cookie $upstream_http_set_cookie","proxy_pass_request_body off","proxy_set_header Content-Length \"\"","proxy_http_version 1.1","proxy_cache_bypass $http_upgrade","proxy_buffers 8 16k","proxy_buffer_size 32k","proxy_ssl_server_name on","proxy_ssl_name $host","proxy_ssl_session_reuse off","proxy_ssl_protocols TLSv1.2 TLSv1.3","proxy_set_header Host $http_host","proxy_set_header Upgrade $http_upgrade","proxy_set_header Connection $connection_upgrade","proxy_set_header X-Real-IP $remote_addr","proxy_set_header Forwarded $proxy_add_forwarded","proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for","proxy_set_header X-Forwarded-Proto $scheme","proxy_set_header X-Forwarded-Host $host","proxy_set_header X-Forwarded-Port $server_port","add_header Strict-Transport-Security \"max-age=63072000\" always","add_header X-XSS-Protection \"1; mode=block\" always","add_header Referrer-Policy \"no-referrer-when-downgrade\" always","add_header Content-Security-Policy \"default-src ''self'' http: https: ws: wss: data: blob: ''unsafe-inline''; frame-ancestors ''self'';\" always","add_header Permissions-Policy \"interest-cohort=()\" always","add_header Strict-Transport-Security \"max-age=31536000; includeSubDomains\" always"}'),
	 ('@','goauthentik_proxy_signin','{internal,"add_header Set-Cookie $auth_cookie","return 302 /outpost.goauthentik.io/start?rd=$request_uri","add_header Strict-Transport-Security \"max-age=63072000\" always","add_header X-XSS-Protection \"1; mode=block\" always","add_header Referrer-Policy \"no-referrer-when-downgrade\" always","add_header Content-Security-Policy \"default-src ''self'' http: https: ws: wss: data: blob: ''unsafe-inline''; frame-ancestors ''self'';\" always","add_header Permissions-Policy \"interest-cohort=()\" always","add_header Strict-Transport-Security \"max-age=31536000; includeSubDomains\" always"}');

INSERT INTO public."_AuthToLocation" ("A","B") VALUES
	 (1,1),
	 (1,2);
